// Code generated by goctl. DO NOT EDIT.
package types

type NullRequest struct {
}

type Request struct {
	Name string `path:"name,options=you|me"`
}

type IdRequest struct {
	Id int64 `path:"id"`
}

type Response struct {
	Message string `json:"message"`
}

type NormalListResponse struct {
	Count int         `json:"count"`
	Data  interface{} `json:"data"`
}

type NormalPageRequest struct {
	Page    int    `form:"page"`
	Size    int    `form:"size"`
	Keyword string `form:"keyword,optional"`
}

type MessagePageRequest struct {
	Page   int    `form:"page"`
	Size   int    `form:"size"`
	ChatId string `path:"chat_id"`
}

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResponse struct {
	UserId       string `json:"user_id"`
	AccessToken  string `json:"access_token"`
	AccessExpire int64  `json:"access_expire"`
	RefreshAfter int64  `json:"refresh_after"`
}

type CreateChannelRequest struct {
	UserId string `json:"user_id"`
}

type UpdatePushTokenRequest struct {
	PushToken string `json:"push_token"`
}

type SendMessageRequest struct {
	ChatId  string `json:"chat_id"`
	Type    string `json:"type"`
	Content string `json:"content"`
}

type WSBaseReq struct {
	Type string `json:"type"`
}

type WSAuthReq struct {
	Token string `json:"token"`
}

type RespConversationMessage struct {
	Id         string `json:"id"`
	ChatId     string `json:"chat_id"`
	Type       string `json:"type"`
	SenderId   string `json:"sender_id"`
	Content    string `json:"content"`
	CreateTime string `json:"create_time"`
}

type RespUser struct {
	Id        string `json:"id"`
	Name      string `json:"name"`
	AvatarUrl string `json:"avatar_url"`
}

type RespConversation struct {
	Id           string   `json:"id"`
	Type         string   `json:"type"`
	ChatId       string   `json:"chat_id"`
	OwnerId      string   `json:"owner_id"`
	OppoUser     RespUser `json:"oppo_user"`
	Name         string   `json:"name"`
	LastReadTime string   `json:"last_read_time"`
	CreateTime   string   `json:"create_time"`
}
