// Code generated by goctl. DO NOT EDIT.
package types

type NullRequest struct {
}

type Request struct {
	Name string `path:"name,options=you|me"`
}

type IdRequest struct {
	Id int64 `path:"id"`
}

type Response struct {
	Message string `json:"message"`
}

type NormalListResponse struct {
	Count int         `json:"count"`
	Data  interface{} `json:"data"`
}

type NormalPageRequest struct {
	Page    int    `form:"page"`
	Size    int    `form:"size"`
	Keyword string `form:"keyword,optional"`
}

type MessagePageRequest struct {
	Page   int    `form:"page"`
	Size   int    `form:"size"`
	ChatId string `path:"chat_id"`
}

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResponse struct {
	UserId       string `json:"user_id"`
	AccessToken  string `json:"access_token"`
	AccessExpire int64  `json:"access_expire"`
	RefreshAfter int64  `json:"refresh_after"`
}

type GetProfileReq struct {
	Uid string `path:"uid"`
}

type CreateChannelRequest struct {
	UserId string `json:"user_id"`
}

type UpdateConversationLastReadTimeRequest struct {
	ChatId string `path:"chat_id"`
}

type UpdatePushTokenRequest struct {
	PushToken string `json:"push_token"`
}

type SendMessageRequest struct {
	ChatId          string `json:"chat_id"`
	MessageClientId string `json:"message_client_id"`
	Type            string `json:"type"`
	Content         string `json:"content"`
}

type RespConversationMessage struct {
	Id              string                         `json:"id"`
	MessageClientId string                         `json:"message_client_id,omitempty"`
	ChatId          string                         `json:"chat_id"`
	Type            string                         `json:"type"`
	SenderId        string                         `json:"sender_id"`
	Content         RespConversationMessageContent `json:"content"`
	SendTime        int64                          `json:"send_time"`
}

type RespConversationMessageContent struct {
	Text    string `json:"text,omitempty"`
	Width   int    `json:"width"`
	Height  int    `json:"height"`
	FileUri string `json:"file_uri"`
}

type RespUser struct {
	Id        string `json:"id"`
	Name      string `json:"name"`
	AvatarUrl string `json:"avatar_url"`
}

type RespConversation struct {
	Id           string                   `json:"id"`
	Type         string                   `json:"type"`
	ChatId       string                   `json:"chat_id"`
	OwnerId      string                   `json:"owner_id"`
	OppoUser     RespUser                 `json:"oppo_user"`
	LastMessage  *RespConversationMessage `json:"last_message"`
	UnreadCount  int                      `json:"unread_count"`
	Name         string                   `json:"name"`
	LastReadTime int64                    `json:"last_read_time"`
	CreateTime   string                   `json:"create_time"`
}
